### ISSUE TITLE
Documentation Site not working anymore

### ISSUE THREAD

**Issue by mark-ellul** [whatgoodisaroad/validity#82]
Hi Wyatt,

The [http://validity.thatscaptaintoyou.com/](http://validity.thatscaptaintoyou.com/) site doesn't work anymore.

Is there any chance that you can migrate the documentation to the github wiki or make a github.io site for this repo?

Regards

Mark

**Comment by whatgoodisaroad** [comment]
Thanks for the suggestion. I've moved the docs into a github.io site at 
http://whatgoodisaroad.github.io/validity/Demos/index.htm
